CLASS zeh_new_agency_sol DEFINITION
  PUBLIC
  FINAL FOR EVENTS OF ZR_AGENCYSOL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZEH_NEW_AGENCY_SOL IMPLEMENTATION.
ENDCLASS.
